#ifndef __DEFS__
#define __DEFS__

typedef uint8_t	BYTE;
typedef uint16_t	WORD;
typedef uint32_t	DWORD;
typedef uint64_t	ULONGLONG;

#define IMAGE_NUMBEROF_DIRECTORY_ENTRIES	16
#define IMAGE_FILE_MACHINE_I386				0x014c //x86
#define IMAGE_FILE_MACHINE_IA64				0x0200 //Intel Itanium
#define IMAGE_FILE_MACHINE_AMD64			0x8664 //x64

#define IMAGE_SUBSYSTEM_UNKNOWN						0
#define IMAGE_SUBSYSTEM_NATIVE						1
#define IMAGE_SUBSYSTEM_WINDOWS_GUI					2
#define IMAGE_SUBSYSTEM_WINDOWS_CUI					3
#define IMAGE_SUBSYSTEM_OS2_CUI						5
#define IMAGE_SUBSYSTEM_POSIX_CUI					7
#define IMAGE_SUBSYSTEM_WINDOWS_CE_GUI				9
#define IMAGE_SUBSYSTEM_EFI_APPLICATION				10
#define IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER		11
#define IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER			12
#define IMAGE_SUBSYSTEM_EFI_ROM						13
#define IMAGE_SUBSYSTEM_XBOX						14
#define IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION	16



#endif
